id: PB16E9B8F
initial_creation_type: input
source_metadata:
  title: Jaiminīyagṛhyasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Gṛhyasūtra
  data entry: members of the Sansknet Project
  contribution to GRETIL: members of the Sansknet Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:49:40.810325'
last_modified_at: '2022-03-09T14:49:40.810337'
